Fixed user not found in active directory issue
wso2-extensions/identity-outbound-auth-email-otp pull request #14
Opened 2017-03-01 09:27 UTC by Kanapriya

2017-03-03 07:24 UTC, malakasilva requested changes
Please check the added comments and arrange a another review before releasing.

2017-03-03 07:24 UTC, malakasilva commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPUtils.java
> +            if (isUserExistence) {
It does not make sense to pass a Boolean parameter and change behavior of a util method. Handle this before calling the method.

2017-03-03 07:24 UTC, malakasilva commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java
> +            boolean isEmailOTPEnabledByUser = EmailOTPUtils.isEmailOTPEnableForLocalUser(username, context, isUserExistence);
No need to do this step if the above is false.

2017-03-03 07:24 UTC, malakasilva commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java
> +            if (isEmailOTPMandatory) {
This is not readable. Please avoid nested if / else blocks and try to resolve it elseif etc.

2017-03-03 07:24 UTC, malakasilva commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java
> +                if (authenticatorProperties != null) {
Again no readability. avoid nested if blocks. 

Eg:- If there are exception cases do those first and return from that at the top.

2017-03-03 07:24 UTC, malakasilva commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java
> +                    log.error("Error while retrieving properties. Authenticator Properties cannot be null");
Why we need to log and throw?

2017-03-09 08:53 UTC, isharak commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java
> +                            (EmailOTPAuthenticatorConstants.IS_EMAILOTP_MANDATORY)));
What is the difference between getting from the context and emailOTP parameters ?

2017-03-09 08:53 UTC, isharak commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java
> +                isEmailOTPMandatory = Boolean.parseBoolean(emailOTPParameters
Same logic is duplicating

2017-03-09 08:53 UTC, isharak commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPUtils.java
> +            tenantAwareUsername = MultitenantUtils.getTenantAwareUsername(String.valueOf(username));
Why do u need to get string value again coz username is a string right ?

2017-03-09 08:53 UTC, isharak commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPUtils.java
> +                payload = String.valueOf(context.getProperty(api + EmailOTPAuthenticatorConstants.PAYLOAD));
Most of the time we get String.valueOf. do we need this all the cases ?

2017-03-09 08:57 UTC, Kanapriya commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java
> +                            (EmailOTPAuthenticatorConstants.IS_EMAILOTP_MANDATORY)));
In tenant when we load the xml file in registry, it will load the parameters in context, so we tried to get the parameters from context.

2017-03-09 08:59 UTC, Kanapriya commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java
> +                isEmailOTPMandatory = Boolean.parseBoolean(emailOTPParameters
Here we check the tenant, if it is super tenant, then get the parameters from the local. if it is tenant, then get the parameters from context if the file upload in registry, if the file not in registry try to get it from local.

2017-03-09 10:26 UTC, Kanapriya commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPUtils.java
> +            tenantAwareUsername = MultitenantUtils.getTenantAwareUsername(String.valueOf(username));
Fixed in 22e867f8e9f420c8ca4a47697302d67387240284

2017-03-09 10:27 UTC, Kanapriya commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPUtils.java
> +                payload = String.valueOf(context.getProperty(api + EmailOTPAuthenticatorConstants.PAYLOAD));
When we get the parameter from context, it returns as object. So that, cast the parameter to String.

2017-03-09 10:34 UTC, malakasilva approved these changes

2017-03-09 10:45 UTC, merged